services:
  redis:
    image: redis:7-alpine
    container_name: inventory-lock-redis
    ports:
      - "6386:6379"
  mysql:
    image: mysql:8.0
    container_name: inventory-lock-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: inventory_lock
      MYSQL_USER: lab
      MYSQL_PASSWORD: lab1234
    ports:
      - "3316:3306"
